### ISSUE TITLE
Is there a way to delete all the keys from fileCache

### ISSUE THREAD

**Issue by shivakumarss** [gadelkareem/cachita#1]
Hello there, 

Is there any way i can invalidate all the keys from fileCache ? 

Thanks.
Shiva

**Comment by gadelkareem** [comment]
It depends on the datastore, for ex, you can delete files directory to remove all file cache.

**Comment by shivakumarss** [comment]
Thanks for the quick reply @gadelkareem 

I am using https://github.com/gadelkareem/cachita/blob/master/cache.go#L14 Interface for all operations and file cache as the datastore. 

So the only way i can delete all the keys from the cache is to delete the files directory and there is no api available right now.

**Comment by gadelkareem** [comment]
That's correct.

**Comment by gadelkareem** [comment]
I just added new func `InvalidateMulti(keys ...string) error` https://github.com/gadelkareem/cachita/blob/master/cache.go#L21 for this
